name: Run tests
on:
  push:
    branches:
      - 'master'
      - 'staging'
  pull_request:
    branches-ignore:
      - 'gh-pages'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install shunit2
      - name: Check out branch
        uses: actions/checkout@v4
      - name: Create the minecraft user
        run: sudo adduser --system minecraft
      - name: Run tests
        run: sudo /bin/bash ./test.sh
